version: '3'

services:
  app:
    container_name: "${APP_NAME:-Docker_bot}_app" # APP_NAME in .env, else Docker_bot
    build: ../
    volumes:
      - ../logs:/code/logs
      - ../last_id.txt:/code/last_id.txt
